### ISSUE TITLE
How does this Github action handle revision hash/number?

### ISSUE THREAD

**Issue by rpdecks** [honeybadger-io/github-upload-sourcemap-action#1]
Errors reported in the Honeybadger dashboard claim there is no source map for the error being reported however...
When I use this Github action, I get an "ok" 200 response from the API and the HB dashboard shows the source map correctly but the revision number doesn't correlate to my Github commit hash. 

At this point, I am suspicious about the revision hash associated with my source map.

Formerly, when I uploaded my source maps via the curl script per the honeybadger documentation I had to include a revision number for it to work properly. I used the git commit hash from my master branch that I used to build and deploy.
## CURL
![image](https://user-images.githubusercontent.com/5845981/165329401-597f3d69-43e0-428e-a041-410c05ea3197.png)

## GIT ACTION
![image](https://user-images.githubusercontent.com/5845981/165328441-9e08a1b0-b2b0-4451-a760-4345ba860dd5.png)  

Should this action also receive an input for `revision` like the curl script?

**Comment by rabidpraxis** [comment]
Hi there @rpdecks! The script uses the sha passed in as an environment variable, which should map to the revision on which the build was run:

https://github.com/honeybadger-io/github-upload-sourcemap-action/blob/b29c7bd4fd222360a25a1522563ca99cdb7633fc/entrypoint.sh#L12

Is that not populating correctly, or were you looking to override it?

**Comment by rpdecks** [comment]
> Hi there @rpdecks! The script uses the sha passed in as an environment variable, which should map to the revision on which the build was run:
> 
> https://github.com/honeybadger-io/github-upload-sourcemap-action/blob/b29c7bd4fd222360a25a1522563ca99cdb7633fc/entrypoint.sh#L12
> 
> Is that not populating correctly, or were you looking to override it?

Thanks for the reply. So I feed the hash to the curl manually via bash but when using this action it's not the right hash and yes, if I could I would override it to make sure it was correct.
The hash should be `9a84a4bc38e5cd4e978b5e99b55d4b6af6a6772e` 

![image](https://user-images.githubusercontent.com/5845981/165389502-dcaa7ace-aff5-4fdf-8783-e5bc7005e390.png)

I'm also interested in why it's wrong. By that I mean the revision on the HB dashboard doesn't match the commit hash I have at the tip of the `master` branch.

For context, if it helps, my own honeybadger action wraps this this one and is a reusable workflow. When I run it from the github actions tab in my repo, I use the version of my prod_deploy workflow that is on the staging branch and it calls my HB action which has this action in it.

This is my action....
```
name: Honeybadger Source Map Upload

on:
  # This sets this flow up like a module, a reusable workflow, designed to be called by others
  workflow_call:
    inputs:
      chunk1_path:
        required: true
        type: string
      chunk2_path:
        required: true
        type: string
      commit_hash:
        required: true
        type: string
    secrets:
      HONEYBADGER_API_KEY:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # currently our app yields 2 primary JS minified chunk files when built
        # matrix strategy effectively runs this job for each of these inputs (ie a loop)
        chunk_file_paths:
          ["${{ inputs.chunk1_path }}", "${{ inputs.chunk2_path }}"]
    steps:
      # Only run this workflow if app == staging/prod
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repo
        id: checkout
        uses: actions/checkout@v2

      - name: Download build directory artifiact
        uses: actions/download-artifact@v2
        with:
          name: prod # this name is set in react_build.yml based on app name
          path: ./client/build

      # the next two steps are gymnastics to construct the paths and URL's the HB action needs
      # at the end of this flow to upload our deployed app's sourcemaps for error monitoring
      - name: Get chunk file name
        # get the file names of the built app's chunk file(s)
        id: chunk
        run: |
          filename="$(basename ${{ matrix.chunk_file_paths }})"
          echo "::set-output name=filename::$filename"

      - name: Set prod minified url
        # construct the url of the built app's chunk file and set as output for HB use in next step
        id: min_url
        run: |
          url=https://mysite.com/static/js/${{ steps.chunk.outputs.filename }};
          echo "::set-output name=url::$url"

      - name: Upload source map to Honeybadger
        run: |
          curl https://api.honeybadger.io/v1/source_maps \
          -F api_key=$API_KEY \
          -F revision=$REVISION \
          -F minified_url=$MINIFIED_URL \
          -F source_map=$SOURCE_MAP \
          -F minified_file=$MINIFIED_FILE
        env:
          API_KEY: ${{ secrets.HONEYBADGER_API_KEY }}
          REVISION: ${{ inputs.commit_hash }}
          MINIFIED_URL: ${{ steps.min_url.outputs.url }}
          SOURCE_MAP: ${{ matrix.chunk_file_paths }}.map
          MINIFIED_FILE: ${{ matrix.chunk_file_paths }}

      # This Github action seems to be missing input for revision which used to correlate to
      # the git commit hash when using the curl method of uploading.
      # - uses: honeybadger-io/github-upload-sourcemap-action@master
      #   with:
      #     api_key: ${{ secrets.HONEYBADGER_API_KEY }}
      #     minified_url: ${{ steps.min_url.outputs.url }}
      #     minified_file: ${{ matrix.chunk_file_paths }}
      #     source_map: ${{ matrix.chunk_file_paths }}.map

```
